/*
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/
#include<iostream>
#include<stdio.h>
using namespace std;

int main()
{
	long long t,i,count=0,n,great=0;
	for(n=1;count<500;n++)
	{
		t=((n*(n+1))/2);
		count=0;
		i=1;
		cout<<"\nt="<<t<<" :";
		while(i<=(t/i))
		{
			//cout<<"Entered while";
			if(t%i==0)
			{
				count=count+2;
				cout<<" "<<i;
			}
			i++;
			//getchar();
		}
		if(great<count)
			great=count;
		cout<<"\ncount : "<<count;
		//getchar();
	}
	cout<<"\nGreatest value : "<<great;
	return 0;
}
